# github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

    ## jdk setting
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # https://github.com/actions/setup-java

    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    ## create application-prod.yml
    - name: make application-prod.yml
      if: contains(github.ref, 'dev')
      run: |
        cd ./src/main/resources
        touch ./application-prod.yml
        echo "${{ secrets.YML_PROD }}" > ./application-prod.yml
      shell: bash

    ## create application-security.yml
    - name: make application-security.yml
      if: contains(github.ref, 'dev')
      run: |
          cd ./src/main/resources
          touch ./application-security.yml
          echo "${{ secrets.YML_SECURITY }}" > ./application-security.yml
      shell: bash

    ## create application-storage.yml
    - name: make application-storage.yml
      if: contains(github.ref, 'dev')
      run: |
          cd ./src/main/resources
          touch ./application-storage.yml
          echo "${{ secrets.YML_OBJECT_STORAGE }}" > ./application-storage.yml
      shell: bash

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew build

    ## docker build & push to production
    - name: Docker build & push to prod
      if: contains(github.ref, 'dev')
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-prod -t ${{ secrets.DOCKER_REPO }}/pinata-server .
          docker push ${{ secrets.DOCKER_REPO }}/pinata-server

    ## deploy to production
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      if: contains(github.ref, 'dev')
      with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          # key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
              sudo docker rm -f $(docker ps -qa)
              sudo docker pull ${{ secrets.DOCKER_REPO }}/pinata-server
              docker-compose up -d
              docker image prune -f

  ## time
  current-time:
    needs: CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH:mm:ss
          utcOffset: "+09:00" # 기준이 UTC이기 때문에 한국시간인 KST를 맞추기 위해 +9시간 추가

      - name: Print Current Time
        run: echo "Current Time=${{steps.current-time.outputs.formattedTime}}" # current-time 에서 지정한 포맷대로 현재 시간 출력
        shell: bash
